enum Style_Tag{
    Stag_Bar = 0,
    Stag_Bar_Active = 1,
    Stag_Base = 2,
    Stag_Pop1 = 3,
    Stag_Pop2 = 4,
    Stag_Back = 5,
    Stag_Margin = 6,
    Stag_Margin_Hover = 7,
    Stag_Margin_Active = 8,
    Stag_List_Item = 9,
    Stag_List_Item_Hover = 10,
    Stag_List_Item_Active = 11,
    Stag_Cursor = 12,
    Stag_At_Cursor = 13,
    Stag_Highlight_Cursor_Line = 14,
    Stag_Highlight = 15,
    Stag_At_Highlight = 16,
    Stag_Mark = 17,
    Stag_Default = 18,
    Stag_Comment = 19,
    Stag_Keyword = 20,
    Stag_Str_Constant = 21,
    Stag_Char_Constant = 22,
    Stag_Int_Constant = 23,
    Stag_Float_Constant = 24,
    Stag_Bool_Constant = 25,
    Stag_Preproc = 26,
    Stag_Include = 27,
    Stag_Special_Character = 28,
    Stag_Ghost_Character = 29,
    Stag_Highlight_Junk = 30,
    Stag_Highlight_White = 31,
    Stag_Paste = 32,
    Stag_Undo = 33,
    Stag_Next_Undo = 34,
    Stag_Back_Cycle_1 = 35,
    Stag_Back_Cycle_2 = 36,
    Stag_Back_Cycle_3 = 37,
    Stag_Back_Cycle_4 = 38,
    Stag_Text_Cycle_1 = 39,
    Stag_Text_Cycle_2 = 40,
    Stag_Text_Cycle_3 = 41,
    Stag_Text_Cycle_4 = 42,
    Stag_COUNT = 43
};

static char *style_tag_names[] = {
    "Bar",
    "Bar_Active",
    "Base",
    "Pop1",
    "Pop2",
    "Back",
    "Margin",
    "Margin_Hover",
    "Margin_Active",
    "List_Item",
    "List_Item_Hover",
    "List_Item_Active",
    "Cursor",
    "At_Cursor",
    "Highlight_Cursor_Line",
    "Highlight",
    "At_Highlight",
    "Mark",
    "Default",
    "Comment",
    "Keyword",
    "Str_Constant",
    "Char_Constant",
    "Int_Constant",
    "Float_Constant",
    "Bool_Constant",
    "Preproc",
    "Include",
    "Special_Character",
    "Ghost_Character",
    "Highlight_Junk",
    "Highlight_White",
    "Paste",
    "Undo",
    "Next_Undo",
    "Back_Cycle_1",
    "Back_Cycle_2",
    "Back_Cycle_3",
    "Back_Cycle_4",
    "Text_Cycle_1",
    "Text_Cycle_2",
    "Text_Cycle_3",
    "Text_Cycle_4",
};
